version = 0.1
[default.deploy.parameters]
stack_name = "diploma-stack"
resolve_s3 = true
s3_prefix = "diploma-stack"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ApiGatewaySourceArn=\"{'Fn::Sub': 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*'}\""
image_repositories = []
