AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DynamoDBStack:
    Properties:
      TemplateURL: dynamodb_tables.yml
    Type: AWS::CloudFormation::Stack
  IAMRolesStack:
    Properties:
      TemplateURL: iam_roles.yml
    Type: AWS::CloudFormation::Stack
  LambdaStack:
    Properties:
      TemplateURL: lambda_functions.yml
    Type: AWS::CloudFormation::Stack
  MatchingPairsApi:
    Properties:
      DefinitionBody:
        info:
          description: API for Matching Pairs game
          title: MatchingPairs Service
          version: '1.0'
        openapi: 3.0.1
        paths:
          /birecords:
            get:
              parameters:
              - description: Page number for pagination (starts from 1)
                in: query
                name: pageNumber
                required: false
                schema:
                  minimum: 1
                  type: integer
              - description: Number of items per page
                in: query
                name: pageSize
                required: false
                schema:
                  minimum: 1
                  type: integer
              responses:
                '200':
                  content:
                    application/json:
                      schema:
                        properties:
                          Items:
                            items:
                              properties:
                                PlayerId:
                                  type: string
                                Score:
                                  type: integer
                              type: object
                            type: array
                          PageNumber:
                            type: integer
                          PageSize:
                            type: integer
                          TotalItems:
                            type: integer
                        type: object
                  description: Paginated list of game records
              summary: Retrieve paginated game records
              x-amazon-apigateway-integration:
                httpMethod: GET
                type: aws_proxy
                uri: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GameRecordsHandler.Arn}/invocations
            post:
              requestBody:
                content:
                  application/json:
                    schema:
                      properties:
                        PlayerId:
                          type: string
                        Score:
                          type: integer
                      required:
                      - PlayerId
                      - Score
                      type: object
                description: Game record to save
                required: true
              responses:
                '200':
                  content:
                    text/plain:
                      schema:
                        type: string
                  description: Record saved successfully
              summary: Save a game record
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GameRecordsHandler.Arn}/invocations
          /records:
            get:
              parameters:
              - description: Page number for pagination (starts from 1)
                in: query
                name: pageNumber
                required: false
                schema:
                  minimum: 1
                  type: integer
              - description: Number of items per page
                in: query
                name: pageSize
                required: false
                schema:
                  minimum: 1
                  type: integer
              responses:
                '200':
                  content:
                    text/plain:
                      schema:
                        type: string
                  description: Get records table
              summary: Get Records Lambda
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetRecordsHandler.Arn}/invocations
          /words:
            get:
              parameters:
              - description: Page number for pagination (starts from 1)
                in: query
                name: pageNumber
                required: false
                schema:
                  minimum: 1
                  type: integer
              - description: Number of items per page
                in: query
                name: pageSize
                required: false
                schema:
                  minimum: 1
                  type: integer
              - description: Specify "random" for random set of word pairs
                in: query
                name: action
                required: false
                schema:
                  enum:
                  - default
                  - random
                  type: string
              responses:
                '200':
                  content:
                    application/json:
                      schema:
                        properties:
                          nextToken:
                            description: Token for the next page
                            type: string
                          words:
                            items:
                              properties:
                                Japanese:
                                  type: string
                                Ukrainian:
                                  type: string
                              type: object
                            type: array
                        type: object
                  description: Paginated or random list of words
              summary: Retrieve paginated or random list of word pairs
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MatchingPairsHandler.Arn}/invocations
      Name: MatchingPairsApi
      StageName: prod
    Type: AWS::Serverless::Api
