AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket where the JSON file is stored.
  JSONFileName:
    Type: String
    Description: Name of the JSON file in the S3 bucket.

Resources:
  # Lambda function for API handling and data loading
  MatchingPairsHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MatchingPairsHandler
      Runtime: dotnet6
      CodeUri: lambda/
      Handler: MatchingPairsLambda::MatchingPairsLambda.Function::FunctionHandler
      Environment:
        Variables:
          TABLE_NAME: !Ref MatchingPairsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MatchingPairsTable
        - S3ReadPolicy:
            BucketName: !Ref S3BucketName

  # DynamoDB table for storing Ukrainian-Japanese word pairs
  MatchingPairsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MatchingPairsTable
      AttributeDefinitions:
        - AttributeName: WordId
          AttributeType: S
      KeySchema:
        - AttributeName: WordId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # Custom resource to load initial data from JSON file in S3 to DynamoDB
  LoadWordsData:
    Type: Custom::PreLoadData
    Properties:
      ServiceToken: !GetAtt MatchingPairsHandler.Arn
      TableName: !Ref MatchingPairsTable
      S3BucketName: !Ref S3BucketName
      JSONFileName: !Ref JSONFileName

  # API Gateway REST API for the Matching Pairs service
  MatchingPairsApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: MatchingPairsApi
      StageName: prod
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: MatchingPairs Service
          description: API for Matching Pairs game similar to Duolingo
          version: '1.0'
        paths:
          /words:
            get:
              summary: Get paginated or random list of Ukrainian-Japanese word pairs
              parameters:
                - name: pageNumber
                  in: query
                  required: false
                  schema:
                    type: integer
                    minimum: 1
                  description: Page number for pagination (starts from 1)
                - name: pageSize
                  in: query
                  required: false
                  schema:
                    type: integer
                    minimum: 1
                  description: Number of items per page
                - name: action
                  in: query
                  required: false
                  schema:
                    type: string
                    enum: [ "default", "random" ]
                  description: Specify "random" to get a random set of word pairs
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MatchingPairsHandler.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
              responses:
                '200':
                  description: List of words with pagination or random selection
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          words:
                            type: array
                            items:
                              type: object
                              properties:
                                Japanese:
                                  type: string
                                Ukrainian:
                                  type: string
                          nextToken:
                            type: string
                            description: Token for the next page (only for paginated responses)

Outputs:
  ApiUrl:
    Description: URL for the API Gateway
    Value: !Sub "https://${MatchingPairsApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  DynamoDBTableName:
    Description: Name of the DynamoDB table
    Value: !Ref MatchingPairsTable
